// qcv.exe -s properties.cs Tutorial.Properties --run

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Diagnostics;

using QCV.Base;
using QCV.Base.Addins;
using QCV.Base.Extensions;

namespace Tutorial {

  [Addin]
  public class Properties : IFilter, IFilterListProvider {
    
    public FilterList CreateFilterList(AddinHost host) {
      return new FilterList() {
        this
      };
    }
    
    private string _name = "John Doe";
    [Description("This specifies your name used for accounting.")]
    public string Name {
      get { return _name; }
      set {_name = value; }
    }
    
    private int _id = 10;
    [Description("This is your unique identifier as generated by the system.")]
    [ReadOnly(true)]
    public int Id {
      get { return _id; }
      set {_id = value; }
    }
    
    private int _hidden = 10;
    [Description("This property won't show up.")]
    [Browsable(false)]
    public int Hidden {
      get { return _hidden; }
      set {_hidden = value; }
    }
    
    public void Execute(Dictionary<string, object> bundle) 
    {}
    
  }
}